### ISSUE TITLE
MenuItems cannot be rendered outside a collection.

### ISSUE THREAD

**Issue by m1guer** [irsyadadl/justd#113]
im getting this error when i try to follow this [example:](https://justd.co/docs/components/overlays/sheet#like-github)
```jsx
Unhandled Runtime Error Error: MenuItem cannot be rendered outside a collection.  Call Stack <unknown> node_modules/@react-aria/collections/dist/packages/@react-aria/collections/src/CollectionBuilder.tsx (167:15) React
```

**Comment by irsyadadl** [comment]
It’s literally a file inside the example folder. How'd you even get an error? Check it out [here](https://github.com/irsyadadl/justd/blob/main/components/docs/overlays/sheet-menu-demo.tsx). I've just tested and don't have any error just like yours. Are you using the latest version of rac?

**Comment by m1guer** [comment]
oh, found what im doing wrong. sorry.
