### ISSUE TITLE
Home page command menu for search breaks visually on mobile chromium browsers

### ISSUE THREAD

**Issue by joncoronel** [irsyadadl/justd#148]
**Describe the bug**
When at the home page for justd on mobile,   opening the search command menu will open up a visually broken menu. Scrolling through the command menu seems to fix it but it's almost always visually buggy on when first opened. This only occurs on chromium browsers on Android. Don't have an iPhone so not sure if it happens on other devices but Firefox does not have this issue. 

**To Reproduce**
1. Go to home page for justd. 
2. Click on the search button at the top
3. Command menu will open up 
4. See visual bug

**Expected behavior**
Command menu should open up and every command in the menu should be visible. 

**Screenshots**
![SmartSelect_20240810_052301_Chrome.jpg](https://github.com/user-attachments/assets/7a91d192-ed33-4c63-b060-afb2c065fa23)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Samsung s21 ultra 
 - OS: Android 14
 - Browser [Chrome, Opera, Brave]
 - Version [Chrome 127.0.6533.103, Opera version  83.1.4388.80509, Brave 1.68.134, Chromium 127.0.6533.88]

**Additional context**
This only occurs on the home page. Is the search command menu is opened from any other page, the visual bug does not occur.

**Comment by irsyadadl** [comment]
This is happened every single time you open or sometimes?

**Comment by irsyadadl** [comment]
Thank you for bringing this to my attention. I'll keep this issue open until it's resolved.

**Comment by irsyadadl** [comment]
@joncoronel how about now ?

**Comment by joncoronel** [comment]
https://github.com/user-attachments/assets/ca35f511-d944-483e-b378-d9e68d9fdc9e

Unfortunately, it still occurs.

**Comment by irsyadadl** [comment]
It seems strange, doesn't it? I tested it on both Android and iOS without any issues. Troubleshooting problems that can't be debugged is challenging, but I'll try a different approach.

**Comment by joncoronel** [comment]
It's possible to debug by connecting an android phone with USB debugging enabled to a desktop and then going to `chrome://inspect/#devices` on the desktop chrome browser. 
I took a quick look but didn't find anything obvious.

**Comment by joncoronel** [comment]
May have found the cause of it.
![justd issue](https://github.com/user-attachments/assets/d0272215-fe52-4cb1-ab67-6a6d74abf393)
This element with the clip path is the issue. Deleting this element resolved the issue. But I narrowed it down further to being caused by the aspect ratio styling. If I simply remove the aspect ratio styles from the element, the issue is fixed. Not sure why that would even cause this issue.

**Comment by irsyadadl** [comment]
@joncoronel how about now, because I've been hide on mobile device at pr #153.

**Comment by joncoronel** [comment]
Yes, that fixed the issue!
Btw, unrelated to this issue, but I noticed the performance on the search command menu is relatively laggy/stuttery on mobile compared to the simple ones found in the command menu page examples. 

Could this just because if the amount of commands? Maybe virtualization can help?

**Comment by irsyadadl** [comment]
Well, this will be another issue actually, so right now you can close it and reopen with another.
