### ISSUE TITLE
CLI Registry not found

### ISSUE THREAD

**Issue by iranzithierry** [irsyadadl/justd#246]
I am trying to start working with justd but i encoutered problem with registry of the cli is not found 
![image](https://github.com/user-attachments/assets/4c6e4312-8605-4a13-8cd9-3e6d0312e2dd)

**Comment by irsyadadl** [comment]
This is strange, even I experienced it too. npmjs remove the package? why?

**Comment by irsyadadl** [comment]
it's because npmjs, now you can. Try again!
