### ISSUE TITLE
Resizable Table has "layout flash"

### ISSUE THREAD

**Issue by mw10013** [irsyadadl/justd#247]
**Describe the bug**

A resizable table seems to have a "layout flash" on initial render and refresh if the width of the table is wider than the minimum widths of all its columns.

**To Reproduce**
1. Render the example code for Resizable (https://getjustd.com/docs/components/collections/table#resizable) in a web page that is wide enough so that the table is wider than the minimum widths of all its columns.
2. Initial render has "layout flash"
3. Refreshing page results in  :layout flash"

Stackblitz repro: https://stackblitz.com/~/github.com/mw10013/rr-justd-sandbox?file=app/lib/components/resizable-table.tsx

NB: Ensure the preview pane for the web page in StackBlitz is wider than the minimum widths of all the columns in the resizable table.

**Expected behavior**

There should be no "layout flash"

**Screenshots**

Stackblitz repro: https://stackblitz.com/~/github.com/mw10013/rr-justd-sandbox?file=app/lib/components/resizable-table.tsx

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari]: chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by irsyadadl** [comment]
It'll update later on #243 , for now, the flash won't gone, but at least, you can add `min-w-full` to the root style on `Table.tsx`.

```tsx
const table = tv({
  slots: {
    root: "table min-w-full
```

**Comment by mw10013** [comment]
Submitted issue upstream: https://github.com/adobe/react-spectrum/issues/7499
