### ISSUE TITLE
MultipleSelect feature or bug

### ISSUE THREAD

**Issue by bycolour2** [irsyadadl/justd#249]
hello

I manualy installed MultipleSelect component, and it's don't work with dynamic options, is it feature or bug?

**Comment by irsyadadl** [comment]
What do you mean dynamic options, can you show the examples of?

**Comment by bycolour2** [comment]
I mean Options that fetched from api, options that empty array at rendering and changes after render is done
For example based on other field etc.

Trying to repro

**Comment by bycolour2** [comment]
> What do you mean dynamic options, can you show the examples of?

(take some guy stackbliz to show the case)

https://stackblitz.com/~/github.com/mw10013/rr-justd-sandbox?file=app/lib/components/resizable-table.tsx

it will be always no options

**Comment by bycolour2** [comment]
So, no answer?

**Comment by irsyadadl** [comment]
It's closed not because no answer. but the fact that you can't make dynamic options is impossible.
