### ISSUE TITLE
Themes may need slightly fix

### ISSUE THREAD

**Issue by sbetav** [irsyadadl/justd#294]
**Bug Description**  
When copying a theme from https://getjustd.com/themes and pasting it into the `css` file, the variants fail to work. This happens because the theme uses `oklch` color format, but the `tailwind.config.ts` expects colors to be in `hsl` format.  

**Steps to Reproduce**  
1. Initialize the library.  
2. Copy a theme from https://getjustd.com/themes.  
3. Paste the theme into the `css` file.  
4. Observe that the variants are not applied correctly.  

**Expected Behavior**  
Color format should be consistent on library initialization and themes tool.

**Comment by irsyadadl** [comment]
The themes are just for tailwind v4 which use 2.x version of the docs. Otherwised, it doesn't work. https://getjustd.com/docs/2.x/getting-started/installation
